- name: install and run nginx
  hosts: all
  become: yes
  tasks:
    - name: install nginx
      ansible.builtin.package:
        name: nginx
        state: installed
    - name: run nginx
      ansible.builtin.service:
        name: nginx
        state: started
        enabled: yes  